# Generated by Django 4.1.3 on 2023-01-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_last_bid_alter_listing_bid_alter_listing_des'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='last_bid',
            field=models.CharField(default='No one offered', max_length=64),
        ),
    ]
